# Primera LGD con historia separada

**Disponibilidad:** estas puertas pertenecen al candidato de desarrollo y todavía no están publicadas en PyPI 2.16.0. Este cuaderno se ejecutó con el [wheel candidato verificado](https://github.com/nexolabs-gh/bayesrisk/actions/runs/39523257538), disponible en el artefacto `candidate-distributions-with-evidence`. Instalar la versión publicada en PyPI no incorpora estas funciones.

Recorrido experimental; requiere `bayesrisk[scoring,excel]`. Datos inventados incluidos en el paquete: 400 operaciones, 300 train, 80 evaluation y 20 abiertas excluidas. Dos operaciones por deudor dentro de una muestra; ningún deudor cruza las muestras elegibles. Objetivo en [0,1] con extremos 0 y 1 y dos covariables numéricas crudas. Las abiertas conservan objetivo vacío.

La institución debe declarar población, disponibilidad y muestras antes del ajuste. El motor no verifica suficiencia semántica ni temporalidad. Las métricas y la media de referencia son descriptivas; no validan calidad ni transportabilidad.

## Ajustar y evaluar

Los seis roles no se infieren. El ID de operación se declara por separado. Sólo train ajusta el modelo; evaluation no cambia sus coeficientes.

In [1]:
from pathlib import Path

import pandas as pd

from bayesrisk import Lgd, Provision
from bayesrisk.ui.datasets import materialize

historia = materialize("lgd_historia_sintetica", workdir=Path("datos"))
lgd = Lgd(historia, target="lgd_observada", features=["deuda_ingreso", "antiguedad_meses"],
          entity="deudor", sample="muestra", default="incumplio", resolved="resuelto",
          id="loan_id", purpose="Demostrar el flujo con datos inventados",
          assumptions=["Historia sintética con muestras y resultado declarados"],
          limitations=["No valida calidad ni transportabilidad"], formats=["csv", "xlsx"])
lgd.run(raise_on_error=True)
lgd.summary("lgd_training")

── Historia de operaciones ──
Archivo: datos/datasets/lgd_historia_sintetica.parquet (copia en bayesrisk-runs/lgd/input/data-<hash>.parquet)
400 filas · 7 columnas
Identificador: loan_id (índice del archivo)
Se conserva toda la historia; las exclusiones se cuentan antes del ajuste
Evidencia de la corrida: bayesrisk-runs/lgd/run
── Entrenamiento LGD ──
300 operaciones de entrenamiento · 80 de evaluación
20 operaciones excluidas, conservadas en la historia
2 covariables crudas; respuesta fraccional con intercepto
Sólo entrenamiento ajusta el predictor y la media de referencia
Las métricas describen la muestra; no certifican calidad ni transportabilidad
⚠ Declaración aportada; suficiencia y temporalidad no verificadas
⚠ Propósito: Demostrar el flujo con datos inventados
Supuestos: Historia sintética con muestras y resultado declarados
Limitaciones: No valida calidad ni transportabilidad
⚠ Procesos abiertos excluidos; representatividad y ausencia de sesgo de selección no demostradas
── Informe y ficha ──
Informe HTML: bayesrisk-runs/lgd/reports/lgd_report.html
Ficha del modelo: bayesrisk-runs/lgd/run/model_card.json
Registro de auditoría: bayesrisk-runs/lgd/run/audit_trail.jsonl
Ejecución: completada

StageSummary(stage='lgd_training', label='Entrenamiento LGD', lines=('300 operaciones de entrenamiento · 80 de evaluación', '20 operaciones excluidas, conservadas en la historia', '2 covariables crudas; respuesta fraccional con intercepto', 'Sólo entrenamiento ajusta el predictor y la media de referencia', 'Las métricas describen la muestra; no certifican calidad ni transportabilidad'), alerts=('Declaración aportada; suficiencia y temporalidad no verificadas', 'Propósito: Demostrar el flujo con datos inventados/nSupuestos: Historia sintética con muestras y resultado declarados/nLimitaciones: No valida calidad ni transportabilidad', 'Procesos abiertos excluidos; representatividad y ausencia de sesgo de selección no demostradas'), table=         Muestra  ... Raíz del error cuadrático medio
0  Entrenamiento  ...                        0.171575
1  Entrenamiento  ...                        0.196807
2     Evaluación  ...                        0.156369
3     Evaluación  ...                        0.176759
[4 rows x 8 columns], formats={})

## Aplicar a otra cartera sin resultado observado

La cartera sintética tiene 6.000 operaciones. La PD constante es ilustrativa. Se elimina la columna LGD: el predictor usa sólo covariables crudas y no vuelve a ajustar. La provisión conserva la fórmula grupal, con detalle prorrateado. Separar muestras declaradas no certifica independencia del pipeline completo.

El CSV y el libro modelo_lgd exportan una tabla global reutilizable, sin llave de alineación; los textos codificados se conservan. No se cargan Study/joblib por HTTP. Los ZIP conservan historia y aplicación por separado. Las huellas y el ID de ajuste que aparecen abajo identifican esta ejecución; cambian con sus entradas o una corrida nueva.

In [2]:
cartera = pd.read_parquet(materialize("provision_interna_generica", workdir=Path("datos")))
cartera = cartera.drop(columns="lgd")
cartera["pd_declarada"] = 0.02  # Sólo ilustración; no es una PD estimada.
provision = Provision(cartera, as_of="as_of_date", portfolio="portfolio",
                      exposure="exposure_amount", pd="pd_declarada", lgd=lgd.model_,
                      id="loan_id", formats=["csv"])
provision.run(raise_on_error=True)
lgd.export_excel()
lgd.export("historia-lgd.zip")
provision.export("aplicacion-lgd.zip")
provision.summary()

── Cartera ──
Archivo: DataFrame en memoria, guardado como bayesrisk-runs/provision/input/data-<hash>.parquet
6.000 filas · 12 columnas
Esquema inferido: 12 columnas
Identificador: loan_id (índice del archivo)
PD externa declarada; esta corrida no ajusta ni calibra la PD
Evidencia de la corrida: bayesrisk-runs/provision/run
── Provisión interna ──
6.000 operaciones · 3 grupos
Exposición: 8.129.332.047 · Provisión: 58.845.153
Agrupación: banda de score
PD externa declarada: no se ajustó ni calibró en esta corrida
El detalle prorratea el total grupal por exposición; no suma productos individuales
La severidad se predice con un modelo de historia separada, sin reajustarlo con esta cartera.
⚠ Declaración aportada; suficiencia y temporalidad no verificadas
⚠ Propósito: Demostrar el flujo con datos inventados
Supuestos: Historia sintética con muestras y resultado declarados
Limitaciones: No valida calidad ni transportabilidad
⚠ La aplicación no acredita independencia ni transportabilidad; no se reajustó LGD
⚠ Ajuste de origen: 2438c5438d5a462d88e2137387919a75
⚠ Huella del config de origen: e0c11cb5b10bc46e71cfa9c7bc9deebff441ffba9792bff4b8d2ce190365cc0e
⚠ Huella de los datos de origen: acd2a43bbcdf59498d60118e95541d58693976fb4ae1f68c3a84d2a1b2f75450
── Informe y ficha ──
Informe HTML: bayesrisk-runs/provision/reports/provision_interna_report.html
Registro de auditoría: bayesrisk-runs/provision/run/audit_trail.jsonl
Ejecución: completada
Provisión interna total: 58.845.153
Excel por etapa: 3 libros en bayesrisk-runs/lgd/excel
Paquete de la corrida: historia-lgd.zip
Paquete de la corrida: aplicacion-lgd.zip

FinalSummary(execution='completada', validation='no aplica: una provisión no tiene veredicto técnico; lo que la cifra supone está en «Supuestos»', figures=(('Provisión interna total', '58.845.153'), ('Exposición total', '8.129.332.047'), ('Operaciones', '6.000'), ('Grupos', '3'), ('Cobertura', '0,72 %')), review=('Provisión interna: Declaración aportada; suficiencia y temporalidad no verificadas', 'Provisión interna: Propósito: Demostrar el flujo con datos inventados/nSupuestos: Historia sintética con muestras y resultado declarados/nLimitaciones: No valida calidad ni transportabilidad', 'Provisión interna: La aplicación no acredita independencia ni transportabilidad; no se reajustó LGD', 'Provisión interna: Ajuste de origen: 2438c5438d5a462d88e2137387919a75', 'Provisión interna: Huella del config de origen: e0c11cb5b10bc46e71cfa9c7bc9deebff441ffba9792bff4b8d2ce190365cc0e', 'Provisión interna: Huella de los datos de origen: acd2a43bbcdf59498d60118e95541d58693976fb4ae1f68c3a84d2a1b2f75450'), decisions=(), files=(('Carpeta del proyecto', 'bayesrisk-runs/provision'), ('Config vigente', 'bayesrisk-runs/provision/config.yaml'), ('Evidencia de la corrida', 'bayesrisk-runs/provision/run'), ('Registro de auditoría', 'bayesrisk-runs/provision/run/audit_trail.jsonl'), ('Informe HTML', 'bayesrisk-runs/provision/reports/provision_interna_report.html')), stages=(StageSummary(stage='data', label='Cartera', lines=('Archivo: DataFrame en memoria, guardado como bayesrisk-runs/provision/input/data-<hash>.parquet', '6.000 filas · 12 columnas', 'Esquema inferido: 12 columnas', 'Identificador: loan_id (índice del archivo)', 'PD externa declarada; esta corrida no ajusta ni calibra la PD', 'Evidencia de la corrida: bayesrisk-runs/provision/run'), alerts=(), table=None, formats={'Filas': 'int', 'Malos': 'int', 'Tasa de malos': 'pct'}), StageSummary(stage='provisioning_internal', label='Provisión interna', lines=('6.000 operaciones · 3 grupos', 'Exposición: 8.129.332.047 · Provisión: 58.845.153', 'Agrupación: banda de score', 'PD externa declarada: no se ajustó ni calibró en esta corrida', 'El detalle prorratea el total grupal por exposición; no suma productos individuales', 'La severidad se predice con un modelo de historia separada, sin reajustarlo con esta cartera.'), alerts=('Declaración aportada; suficiencia y temporalidad no verificadas', 'Propósito: Demostrar el flujo con datos inventados/nSupuestos: Historia sintética con muestras y resultado declarados/nLimitaciones: No valida calidad ni transportabilidad', 'La aplicación no acredita independencia ni transportabilidad; no se reajustó LGD', 'Ajuste de origen: 2438c5438d5a462d88e2137387919a75', 'Huella del config de origen: e0c11cb5b10bc46e71cfa9c7bc9deebff441ffba9792bff4b8d2ce190365cc0e', 'Huella de los datos de origen: acd2a43bbcdf59498d60118e95541d58693976fb4ae1f68c3a84d2a1b2f75450'), table=                            Grupo  ...    Provisión
group_key                          ...
consumo_senior|banda_01  banda_01  ...  19398642.10
microempresa|banda_01    banda_01  ...  20188916.86
nomina|banda_01          banda_01  ...  19257594.10
[3 rows x 8 columns], formats={'Operaciones': 'int', 'Exposición': 'num2', 'Provisión': 'num2', 'PD del grupo': 'pct', 'LGD del grupo': 'pct', 'Tasa de pérdida': 'pct'}), StageSummary(stage='report', label='Informe y ficha', lines=('Informe HTML: bayesrisk-runs/provision/reports/provision_interna_report.html', 'Registro de auditoría: bayesrisk-runs/provision/run/audit_trail.jsonl'), alerts=(), table=None, formats={})))